### ISSUE TITLE
cif_img_1.8.5.dic

### ISSUE THREAD

**Issue by publcif** [jamesrhester/ImgCIFHandler.jl#11]
_array_data_external_data.archive_format is not in the new imgCIF dictionary and I dont think there is an alternative?

**Comment by jamesrhester** [comment]
Yes, I'm just adapting to all those changes from the latest official version. I've alerted the imgCIF people, see https://github.com/yayahjb/cbflib/issues/46. Meanwhile there may be some residual issues with ImgCIFHandler as I debug the updates.

**Comment by jamesrhester** [comment]
The new data names (except for one) are now present in cif_img_1.8.6.dic and are recognised correctly by ImgCIFHandler.
