### ISSUE TITLE
Extracting a sample image from an archive for validation purposes

### ISSUE THREAD

**Issue by publcif** [jamesrhester/ImgCIFHandler.jl#5]
When testing archived images, would it be prudent to extract just the first image in an archive (if possible) rather than seeking the first image as listed in the CIF (under _array_data.external_archive_path), just in case the order of images (frames) in the CIF is not the same as stored in the actual archive (potentially meaning that the entire archive has to be streamed before identifying the first occurence of a particular frame). For example in the case of a tar file, the archive could be queried just to dump out the details of the first file found, using something like
 curl -s https://zenodo.org/record/5886687/files/cbf_b4_1.tar.bz2 | tar -tjv -f - | awk -F\n '$NF != "" { print $NF; exit }'
then that file could be extracted and tested according to the current procedures (in addition checking that it is indeed listed in the CIF)?
Alternatively, could a 'timeout'  be applied when seeking individual files in a huge archive?

**Comment by jamesrhester** [comment]
I agree this would be an improvement. One technicality: should only stop after the first non-directory entry in the tar file. What do you think of `curl -s xxxx | tar -tjvf - | awk '$3 > 0 { print $NF ; exit }'`?

**Comment by publcif** [comment]
Yes - much better

**Comment by jamesrhester** [comment]
The latest version (0.2.0) implements this, might need some bug checking.
