### ISSUE TITLE
peek_image tar process

### ISSUE THREAD

**Issue by publcif** [jamesrhester/ImgCIFHandler.jl#7]
In the peek_image function in ImgCIFHandler.jl I had to add ingnorestatus=true in the tar step in the pipeline as without it the termination of the tar command seemed to force an error before anything had been written to stdout:

push!(cmd_list, Cmd(`tar -t -v $decomp_option -f -`,ignorestatus=true))

**Comment by jamesrhester** [comment]
Thanks for that!
